// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type ConfigDefault struct {
	ID       int64
	Name     string
	FileName string
	Path     string
	Program  string
	Content  string
}

type RegisteredProgram struct {
	ID       int64
	Program  string
	FileName string
}
