// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package database

import (
	"context"
)

const getAllConfigs = `-- name: GetAllConfigs :many
SELECT content, name FROM config_defaults
`

type GetAllConfigsRow struct {
	Content string
	Name    string
}

func (q *Queries) GetAllConfigs(ctx context.Context) ([]GetAllConfigsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllConfigsRow
	for rows.Next() {
		var i GetAllConfigsRow
		if err := rows.Scan(&i.Content, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfigDefaultByName = `-- name: GetConfigDefaultByName :one
SELECT content, name FROM config_defaults WHERE name = ?
`

type GetConfigDefaultByNameRow struct {
	Content string
	Name    string
}

func (q *Queries) GetConfigDefaultByName(ctx context.Context, name string) (GetConfigDefaultByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getConfigDefaultByName, name)
	var i GetConfigDefaultByNameRow
	err := row.Scan(&i.Content, &i.Name)
	return i, err
}

const insertConfigDefaults = `-- name: InsertConfigDefaults :exec
INSERT INTO config_defaults
    (name, file_name, program, content)
VALUES
    (?, ?, ?, ?)
`

type InsertConfigDefaultsParams struct {
	Name     string
	FileName string
	Program  string
	Content  string
}

func (q *Queries) InsertConfigDefaults(ctx context.Context, arg InsertConfigDefaultsParams) error {
	_, err := q.db.ExecContext(ctx, insertConfigDefaults,
		arg.Name,
		arg.FileName,
		arg.Program,
		arg.Content,
	)
	return err
}
